my_project:
  outputs:
    dev:
      dbname: weather_data
      host: weather_db
      pass: weather_pass
      port: 5432
      schema: dev
      threads: 4
      type: postgres
      user: weather_user
  target: dev
